# Generated by Django 5.1.3 on 2024-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0020_auto_20210527_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Transportation", "Transportation"),
                    ("Entertainment", "Entertainment"),
                    ("Shopping", "Shopping"),
                    ("Bills & Subscriptions", "Bills & Subscriptions"),
                    ("Other", "Other"),
                ],
                max_length=21,
                null=True,
            ),
        ),
    ]
