# Generated by Django 5.1.3 on 2024-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0021_alter_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                default="Monthly",
                max_length=10,
            ),
        ),
    ]
